Repository hato-cc-legacy/front-end, pull requests merged in 2024-08, with the labels that each got.

#20 Delete cards + Edit cards
  package-lock.json
  package.json
  src/components/Card.tsx
  src/components/CreateCardWindow.tsx
  src/components/DeleteCard.tsx
  src/components/styles/Card.css
  src/components/styles/DeleteCard.css
  src/main.css
  src/pages/Index.tsx
  src/pages/UserPage.tsx
  src/util/util.tsx
Labels: bug, enhancement

#23 Feat: Add register new user
  src/App.tsx
  src/api/session.tsx
  src/components/Header.tsx
  src/pages/Register.tsx
Labels: enhancement

#24 Fix: cannot deploy for unused var
  src/components/Card.tsx
Labels: bug

#25 Fix: Refresh after edit or delete
  src/components/Card.tsx
  src/components/ChangeCard.tsx
  src/components/DeleteCard.tsx
  src/pages/Index.tsx
  src/pages/UserPage.tsx
Labels: bug

#16 feat: report button on card and comments
  src/api/report.tsx
  src/components/Card.tsx
  src/components/CardComment.tsx
  src/components/LikesDislikesButtons.tsx
  src/components/assets/Report.tsx
  src/components/styles/CardComment.css
  src/components/styles/LikesDislikesButtons.css
  src/interfaces/CommentsType.tsx
  src/pages/UserPage.tsx
Labels: enhancement
